site_name: My Docs

nav:
    - Home: index.md
    - Developer Guide: 
        - Grid Adventure Enviroment: developer_documentation/grid_adventure_enviroment.md 
        - Game Representation: developer_documentation/game_representation.md 
        - Entity Classes: developer_documentation/entities.md
        - Action Classes: developer_documentation/action.md
        - Agent Class: developer_documentation/agent.md
